### ISSUE TITLE
Crashing after login

### ISSUE THREAD

**Issue by esraaalaain** [QuickBlox/quickblox-flutter-samples#5]
The app crashes after login on an android device with outputs as follows.

```
BODY
D/QBASDK  (20033):     '{"errors":{"details":"Internal Server Error"}}'
D/QBASDK  (20033):
D/AndroidRuntime(20033): Shutting down VM
E/AndroidRuntime(20033): FATAL EXCEPTION: main
E/AndroidRuntime(20033): Process: com.quickblox.quickblox_sdk_example, PID: 20033
E/AndroidRuntime(20033): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 12 path $.errors
E/AndroidRuntime(20033): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
E/AndroidRuntime(20033): 	at com.google.gson.Gson.fromJson(Gson.java:927)
E/AndroidRuntime(20033): 	at com.google.gson.Gson.fromJson(Gson.java:892)
E/AndroidRuntime(20033): 	at com.google.gson.Gson.fromJson(Gson.java:841)
E/AndroidRuntime(20033): 	at com.google.gson.Gson.fromJson(Gson.java:813)
E/AndroidRuntime(20033): 	at com.quickblox.core.parser.QBJsonErrorParser.parseError(Unknown Source:67)
E/AndroidRuntime(20033): 	at com.quickblox.core.result.RestResult.parseErrors(Unknown Source:4)
E/AndroidRuntime(20033): 	at com.quickblox.core.result.RestResult.processResponse(Unknown Source:16)
E/AndroidRuntime(20033): 	at com.quickblox.core.result.RestResult.setResponse(Unknown Source:25)
E/AndroidRuntime(20033): 	at com.quickblox.core.parser.QBJsonParser.parse(Unknown Source:21)
E/AndroidRuntime(20033): 	at com.quickblox.auth.session.Query$VersionEntityCallback.completedWithResponse(Unknown Source:26)
E/AndroidRuntime(20033): 	at com.quickblox.auth.session.Query.completedWithResponse(Unknown Source:11)
E/AndroidRuntime(20033): 	at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(Unknown Source:48)
E/AndroidRuntime(20033): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20033): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(20033): 	at android.app.ActivityThread.main(ActivityThread.java:8037)
E/AndroidRuntime(20033): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20033): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(20033): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime(20033): Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 12 path $.errors
E/AndroidRuntime(20033): 	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
E/AndroidRuntime(20033): 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
E/AndroidRuntime(20033): 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
E/AndroidRuntime(20033): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
E/AndroidRuntime(20033): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
E/AndroidRuntime(20033): 	... 18 more
I/Process (20033): Sending signal. PID: 20033 SIG: 9
Lost connection to device.
```

**Comment by ghost** [comment]
@esraaalaain Hello,

This is Nikolay from QuickBlox support.

Please double-check if the issue persists.

Also, please make sure that you followed our documentation:
[https://docs.quickblox.com/docs/flutter-quick-start](https://docs.quickblox.com/docs/flutter-quick-start)

To investigate the issue, please provide me with the following points:
1. What SDK version are you using?
Please make sure that you use the latest version of the QuickBlox Flutter SDK:
[https://pub.dev/packages/quickblox_sdk/versions/0.6.3-beta](https://pub.dev/packages/quickblox_sdk/versions/0.6.3-beta)
2. Is this issue intermittent or permanent?
3. Are there any other preconditions and steps to reproduce?
4. Please provide us with full REST + XMPP + WebRTC logs as an attachment in .txt format. 
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://quickblox.kayako.com/article/368-how-can-i-enable-quickblox-logs)
5. Version of the platform (e.g. Android 11).
6. Devices in use (e.g. Redmi 8).
7. Flutter version.
8. Dart version.
